### ISSUE TITLE
International not working

### ISSUE THREAD

**Issue by StevenH123** [scott113341/southwest-price-drop-bot#19]
It was working a week or so ago. I'm guessing WN changed something?

note: my line numbers are slightly different than yours as I'm running a locally edited version.

```
TypeError: Cannot read property '1' of null
    at parseTrip (/app/lib/bot/get-price.js:66:34)
    at $.toArray.forEach.e (/app/lib/bot/get-price.js:47:62)
    at Array.forEach (anonymous)
    at getFlights (/app/lib/bot/get-price.js:47:49)
    at anonymous
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Sadly, I'm a windows c++ guy, so I don't know how to debug in this environment to see the output of getPage(params)

Thanks for all you've done with this project, you've saved me some money! Do you have a favorite charity?

**Comment by minamhere** [comment]
I noticed the same thing for domestic flights. I found this regex that seems to work well:

`      const price_ = priceStr.match(/(\d{2,3})\.?\d{0,2}@\w@.*@(\d{2,3}\.\d{2})@\1/);
`

My line numbers are also different, but that should just replace the `const price` definition. I have a few other changes that I'm going to review this weekend and submit a pull request about. I haven't checked it against any international flights, but might be worth a try?

**Comment by scott113341** [comment]
Hey @StevenH123 and @minamhere, thanks for the bug report.  I fixed this bug in [this](https://github.com/scott113341/southwest-price-drop-bot/commit/166493fe7f6ac201c139b43b65df899fa7615fbb) commit; let me know if that works for you!  

As for charities, you can't go wrong with the [EFF](https://www.eff.org/)

**Comment by StevenH123** [comment]
I pulled the latest code down before I opened the ticket. I think
International is still broken.

**Comment by StevenH123** [comment]
I'm sure there's a better way to do this but, to get international working, I did the following in get-price.js:

change
    const priceStr = $(e).siblings('.product_price').text();
to
    const priceStr = (international) ? str : $(e).siblings('.product_price').text();

**Comment by scott113341** [comment]
@StevenH123 thanks, it was indeed broken for international flights.  Fixed now with your solution.  Thanks for the report!
